# Generated by Django 5.1.5 on 2025-01-29 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_created_at_user_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companyFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
