# Generated by Django 5.1.5 on 2025-01-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_companyfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companyFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.companyindexmodel'),
        ),
    ]
